name: CLJS NodeJS
on: [push, pull_request]
jobs:
  node:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1413

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.8.0

      - name: Install Shadow
        run: npm install shadow-cljs

      - name: Run Tests
        run: ./ci/run_tests_js.sh

