name: NodeJS
on: [push, pull_request]
jobs:
  node:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          java-version: 1.11
          distribution: 'zulu'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.17.1
      - name: Install Npm Modules
        run: npm ci

      - name: Run Tests
        run: ./ci/run_tests_js.sh
