name: JVM
on: [push, pull_request]
jobs:
  clojure:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1413

      - name: Run tests
        run: ./ci/run_tests_jvm.sh

