name: Browser
on: [push, pull_request]
jobs:
  browser:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.727

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.8.0

      - name: Install Shadow
        run: npm install --also dev

      - name: Run Tests
        run: ./ci/run_tests_browser.sh

